In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import  load_iris
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score, ShuffleSplit

In [4]:
iris = load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [5]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [16]:
model_dt = DecisionTreeClassifier()
model_lr = LogisticRegression(solver='lbfgs', max_iter=10000, multi_class='auto')
model_svm = SVC(gamma='auto')
model_rf = RandomForestClassifier(n_estimators=40)

score_dt = []
score_lr = []
score_svm = []
score_rf = []

In [17]:
score_dt = cross_val_score(model_dt, iris.data, iris.target, cv=3)
score_dt

array([0.98039216, 0.92156863, 1.        ])

In [18]:
np.average(score_dt)

0.9673202614379085

In [19]:
score_lr = cross_val_score(model_lr, iris.data, iris.target, cv=3)
score_lr

array([0.98039216, 0.94117647, 1.        ])

In [20]:
np.average(score_lr)

0.9738562091503268

In [21]:
score_svm = cross_val_score(model_svm, iris.data, iris.target, cv=3)
score_svm

array([0.98039216, 0.96078431, 0.97916667])

In [22]:

np.average(score_svm)

0.9734477124183006

In [ ]:
score_rf = cross_val_score(model_rf, iris.data, iris.target, cv=3)
score_rf